# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{acts_as_static_controller}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Vlad Alive"]
  s.date = %q{2009-11-30}
  s.description = %q{Rails Plugin: Creates StaticPages Controller to serve static pages.}
  s.email = %q{vladalive@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "acts_as_static_controller.gemspec",
     "app/controllers/static_pages_controller.rb",
     "init.rb",
     "install.rb",
     "lib/acts_as_static_controller.rb",
     "lib/acts_as_static_controller/acts_as_static_controller.rb",
     "lib/acts_as_static_controller/routing.rb",
     "tasks/acts_as_static_controller_tasks.rake",
     "test/acts_as_static_controller_test.rb",
     "test/test_helper.rb",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/vladalive/acts_as_static_controller}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Rails Plugin: Creates StaticPages Controller to serve static pages.}
  s.test_files = [
    "test/acts_as_static_controller_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

